version: 2

before:
  hooks:
  - make clean
  - make dep
  - make build
  - make check

builds:
- id: grpcbin
  main: .
  binary: grpcbin
  env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: windows
    goarch: arm64

archives:
- builds:
  - grpcbin
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  wrap_in_directory: false
  format: tar.gz
  files:
  - LICENSE

changelog:
  sort: asc

release:
  github:
    owner: anddd7
    name: grpcbin
